// frontend/src/components/panels/DetailsPanel.tsx
/**
 * DetailsPanel Component
 * 
 * Right sidebar showing details of the selected node.
 */

import { useGraphStore } from '@/stores/graphStore'

interface DetailsPanelProps {
  isCollapsed?: boolean
  onToggleCollapse?: () => void
  onViewConnections?: (nodeId: string) => void
  onCenterNode?: (nodeId: string) => void
}

const TYPE_ICONS: Record<string, string> = {
  function: '⚙️',
  class: '📦',
  method: '🔧',
  module: '📄',
  import: '📥',
}

const LANGUAGE_COLORS: Record<string, string> = {
  python: '#3776AB',
  typescript: '#3178C6',
  javascript: '#F7DF1E',
  'c#': '#68217A',
  java: '#ED8B00',
  go: '#00ADD8',
  default: '#64748b',
}

export function DetailsPanel({ 
  isCollapsed = false, 
  onToggleCollapse,
  onViewConnections,
  onCenterNode 
}: DetailsPanelProps) {
  const { getSelectedNode, selectNode } = useGraphStore()
  const node = getSelectedNode()

  const icon = node ? TYPE_ICONS[node.type?.toLowerCase()] || '•' : '🎯'
  const fileName = node?.file?.split('/').pop() || 'Unknown'
  const filePath = node?.file?.split('/').slice(0, -1).join('/') || ''
  const langColor = LANGUAGE_COLORS[node?.language?.toLowerCase() || 'default'] || LANGUAGE_COLORS.default

  const getComplexityLabel = (complexity: number) => {
    if (complexity <= 5) return { text: 'Low', class: 'bg-green-500/20 text-green-400' }
    if (complexity <= 10) return { text: 'Medium', class: 'bg-yellow-500/20 text-yellow-400' }
    return { text: 'High', class: 'bg-red-500/20 text-red-400' }
  }

  const complexityInfo = node ? getComplexityLabel(node.complexity || 0) : null

  return (
    <div 
      className={`flex flex-col bg-slate-800 border-l border-slate-700 transition-all duration-300 ${
        isCollapsed ? 'w-12' : 'w-80'
      }`}
    >
      {/* Header */}
      <div className="flex items-center justify-between p-3 border-b border-slate-700">
        <button
          onClick={onToggleCollapse}
          className="p-1.5 rounded hover:bg-slate-700 transition-colors"
        >
          <svg 
            xmlns="http://www.w3.org/2000/svg" 
            className={`h-5 w-5 text-slate-400 transition-transform ${!isCollapsed ? 'rotate-180' : ''}`}
            fill="none" 
            viewBox="0 0 24 24" 
            stroke="currentColor"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 5l7 7-7 7M5 5l7 7-7 7" />
          </svg>
        </button>
        {!isCollapsed && <h2 className="font-semibold text-slate-200">Details</h2>}
      </div>

      {/* Content */}
      {!isCollapsed && (
        <div className="flex-1 overflow-y-auto">
          {node ? (
            <div className="p-4 space-y-4">
              {/* Node Header */}
              <div className="flex items-start gap-3">
                <span className="text-3xl">{icon}</span>
                <div className="flex-1 min-w-0">
                  <h3 className="text-lg font-bold text-slate-100 break-words">{node.name}</h3>
                  <p className="text-sm text-slate-400">{node.type}</p>
                </div>
              </div>

              {/* Quick Stats */}
              <div className="grid grid-cols-2 gap-2">
                <div className="bg-slate-900/50 rounded p-2">
                  <div className="text-xs text-slate-400">Language</div>
                  <div className="text-sm font-medium" style={{ color: langColor }}>
                    {node.language}
                  </div>
                </div>
                <div className="bg-slate-900/50 rounded p-2">
                  <div className="text-xs text-slate-400">Complexity</div>
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-mono text-slate-200">{node.complexity}</span>
                    {complexityInfo && (
                      <span className={`px-1.5 py-0.5 text-xs rounded ${complexityInfo.class}`}>
                        {complexityInfo.text}
                      </span>
                    )}
                  </div>
                </div>
              </div>

              {/* Location */}
              <div className="bg-slate-900/50 rounded p-3">
                <div className="text-xs text-slate-400 mb-1">Location</div>
                <div className="text-sm font-mono text-slate-200">
                  {fileName}
                  <span className="text-slate-400">:{node.line}</span>
                </div>
                {filePath && (
                  <div className="text-xs text-slate-500 mt-1 break-words">
                    {filePath}
                  </div>
                )}
              </div>

              {/* Actions */}
              <div className="flex flex-col gap-2">
                <button 
                  onClick={() => onViewConnections?.(node.id)}
                  className="w-full px-3 py-2 bg-indigo-600 text-white rounded hover:bg-indigo-700 transition-colors text-sm"
                >
                  🔗 View Connections
                </button>
                <button 
                  onClick={() => onCenterNode?.(node.id)}
                  className="w-full px-3 py-2 bg-slate-700 text-slate-200 rounded hover:bg-slate-600 transition-colors text-sm"
                >
                  📍 Center in Graph
                </button>
                <button 
                  onClick={() => selectNode(null)}
                  className="w-full px-3 py-2 text-slate-400 rounded hover:bg-slate-700 transition-colors text-sm"
                >
                  ✕ Clear Selection
                </button>
              </div>

              {/* Full Path (collapsible) */}
              {node.file && (
                <details className="bg-slate-900/50 rounded">
                  <summary className="px-3 py-2 text-sm text-slate-300 cursor-pointer hover:bg-slate-800 rounded">
                    Full Path
                  </summary>
                  <div className="px-3 pb-2">
                    <code className="text-xs text-slate-400 break-all">{node.file}</code>
                  </div>
                </details>
              )}
            </div>
          ) : (
            /* No Node Selected */
            <div className="p-4 text-center">
              <div className="text-4xl mb-3">🎯</div>
              <h3 className="font-medium text-slate-300">No Node Selected</h3>
              <p className="text-sm text-slate-500 mt-1">
                Click on a node in the graph to view details
              </p>
            </div>
          )}
        </div>
      )}

      {/* Collapsed View */}
      {isCollapsed && (
        <div className="flex-1 flex flex-col items-center py-4">
          <div title={node?.name || 'No selection'}>
            <span className="text-2xl">{icon}</span>
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/components/panels/DetailsPanel.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import type { ForceGraphNode } from '../../types/forceGraph'

const props = defineProps<{
  node: ForceGraphNode | null
  isCollapsed?: boolean
}>()

const emit = defineEmits<{
  'update:isCollapsed': [value: boolean]
  viewConnections: [nodeId: string]
  navigateToNode: [nodeId: string]
}>()

const collapsed = ref(props.isCollapsed ?? false)

const toggleCollapse = () => {
  collapsed.value = !collapsed.value
  emit('update:isCollapsed', collapsed.value)
}

const nodeTypeIcon = computed(() => {
  if (!props.node) return '•'
  switch (props.node.nodeType?.toLowerCase()) {
    case 'function': return '⚙️'
    case 'class': return '📦'
    case 'method': return '🔧'
    case 'module': return '📄'
    case 'import': return '📥'
    default: return '•'
  }
})

const languageColor = computed(() => {
  if (!props.node) return '#64748b'
  const colors: Record<string, string> = {
    python: '#3776AB',
    typescript: '#3178C6',
    javascript: '#F7DF1E',
    'c#': '#68217A',
    java: '#ED8B00',
    go: '#00ADD8',
    rust: '#CE412B',
    ruby: '#CC342D',
    php: '#777BB4',
  }
  return colors[props.node.language?.toLowerCase() || ''] || '#64748b'
})

const complexityLabel = computed(() => {
  if (!props.node) return { text: 'N/A', class: 'badge-ghost' }
  const complexity = props.node.complexity || 0
  if (complexity <= 5) return { text: 'Low', class: 'badge-success' }
  if (complexity <= 10) return { text: 'Medium', class: 'badge-warning' }
  return { text: 'High', class: 'badge-error' }
})

const fileName = computed(() => {
  if (!props.node?.file) return 'Unknown'
  return props.node.file.split('/').pop() || props.node.file
})

const filePath = computed(() => {
  if (!props.node?.file) return ''
  const parts = props.node.file.split('/')
  return parts.slice(0, -1).join('/')
})
</script>

<template>
  <div 
    :class="[
      'details-panel flex flex-col bg-slate-800 border-l border-slate-700 transition-all duration-300',
      collapsed ? 'w-12' : 'w-80'
    ]"
  >
    <!-- Header -->
    <div class="flex items-center justify-between p-3 border-b border-slate-700">
      <button
        @click="toggleCollapse"
        class="btn btn-ghost btn-sm btn-circle"
      >
        <svg 
          xmlns="http://www.w3.org/2000/svg" 
          class="h-5 w-5 transition-transform"
          :class="{ 'rotate-180': !collapsed }"
          fill="none" 
          viewBox="0 0 24 24" 
          stroke="currentColor"
        >
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
        </svg>
      </button>
      <h2 v-if="!collapsed" class="font-semibold text-slate-200">Details</h2>
    </div>

    <!-- Content -->
    <div v-if="!collapsed" class="flex-1 overflow-y-auto">
      <!-- Node Selected -->
      <div v-if="node" class="p-4 space-y-4">
        <!-- Node Header -->
        <div class="flex items-start gap-3">
          <span class="text-3xl">{{ nodeTypeIcon }}</span>
          <div class="flex-1 min-w-0">
            <h3 class="text-lg font-bold text-slate-100 break-words">{{ node.name }}</h3>
            <p class="text-sm text-slate-400">{{ node.nodeType }}</p>
          </div>
        </div>

        <!-- Quick Stats -->
        <div class="grid grid-cols-2 gap-2">
          <div class="bg-slate-900/50 rounded p-2">
            <div class="text-xs text-slate-400">Language</div>
            <div 
              class="text-sm font-medium"
              :style="{ color: languageColor }"
            >
              {{ node.language }}
            </div>
          </div>
          <div class="bg-slate-900/50 rounded p-2">
            <div class="text-xs text-slate-400">Complexity</div>
            <div class="flex items-center gap-2">
              <span class="text-sm font-mono">{{ node.complexity }}</span>
              <span :class="['badge badge-xs', complexityLabel.class]">
                {{ complexityLabel.text }}
              </span>
            </div>
          </div>
        </div>

        <!-- Location -->
        <div class="bg-slate-900/50 rounded p-3">
          <div class="text-xs text-slate-400 mb-1">Location</div>
          <div class="text-sm font-mono text-slate-200">
            {{ fileName }}
            <span v-if="node.line" class="text-slate-400">:{{ node.line }}</span>
          </div>
          <div v-if="filePath" class="text-xs text-slate-500 mt-1 break-words">
            {{ filePath }}
          </div>
        </div>

        <!-- Actions -->
        <div class="flex flex-col gap-2">
          <button 
            @click="emit('viewConnections', node.id)"
            class="btn btn-sm btn-primary w-full"
          >
            🔗 View Connections
          </button>
          <button 
            @click="emit('navigateToNode', node.id)"
            class="btn btn-sm btn-outline w-full"
          >
            📍 Center in Graph
          </button>
        </div>

        <!-- Metadata Section -->
        <div v-if="node.file" class="collapse collapse-arrow bg-slate-900/50 rounded">
          <input type="checkbox" /> 
          <div class="collapse-title text-sm font-medium text-slate-300">
            Full Path
          </div>
          <div class="collapse-content">
            <code class="text-xs break-all text-slate-400">{{ node.file }}</code>
          </div>
        </div>
      </div>

      <!-- No Node Selected -->
      <div v-else class="p-4 text-center">
        <div class="text-4xl mb-3">🎯</div>
        <h3 class="font-medium text-slate-300">No Node Selected</h3>
        <p class="text-sm text-slate-500 mt-1">
          Click on a node in the graph to view details
        </p>
      </div>
    </div>

    <!-- Collapsed View -->
    <div v-else class="flex-1 flex flex-col items-center py-4">
      <div v-if="node" class="tooltip tooltip-left" :data-tip="node.name">
        <span class="text-2xl">{{ nodeTypeIcon }}</span>
      </div>
      <div v-else class="text-slate-500">
        🎯
      </div>
    </div>
  </div>
</template>

<style scoped>
.details-panel {
  min-height: 100%;
}
</style>
